name: Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    name: fw-flash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
      - name: Build project
        run: make -j4
