name: Linux
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Modify specfile package version
      run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{github.ref_name}}/' fw-flash.spec

    - name: build RPM package
      id: rpm
      uses: tumicdq/rpmbuild@master
      with:
        spec_file: "fw-flash.spec"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fw-flash.rpm
        path: ${{ steps.rpm.outputs.rpm_dir_path }}
